--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Homebrew)
-- Dumped by pg_dump version 15.13 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: feed_follows; Type: TABLE; Schema: public; Owner: npr
--

CREATE TABLE public.feed_follows (
    id uuid NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    user_id uuid NOT NULL,
    feed_id uuid NOT NULL
);


ALTER TABLE public.feed_follows OWNER TO npr;

--
-- Name: feeds; Type: TABLE; Schema: public; Owner: npr
--

CREATE TABLE public.feeds (
    id uuid NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    name character varying(255) NOT NULL,
    url character varying(255) NOT NULL,
    user_id uuid NOT NULL,
    last_fetched_at timestamp without time zone
);


ALTER TABLE public.feeds OWNER TO npr;

--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: npr
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.goose_db_version OWNER TO npr;

--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: npr
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: posts; Type: TABLE; Schema: public; Owner: npr
--

CREATE TABLE public.posts (
    id uuid NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    title text,
    url text NOT NULL,
    description text,
    published_at timestamp without time zone,
    feed_id uuid NOT NULL
);


ALTER TABLE public.posts OWNER TO npr;

--
-- Name: users; Type: TABLE; Schema: public; Owner: npr
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO npr;

--
-- Name: feed_follows feed_follows_pkey; Type: CONSTRAINT; Schema: public; Owner: npr
--

ALTER TABLE ONLY public.feed_follows
    ADD CONSTRAINT feed_follows_pkey PRIMARY KEY (id);


--
-- Name: feed_follows feed_follows_user_id_feed_id_key; Type: CONSTRAINT; Schema: public; Owner: npr
--

ALTER TABLE ONLY public.feed_follows
    ADD CONSTRAINT feed_follows_user_id_feed_id_key UNIQUE (user_id, feed_id);


--
-- Name: feeds feeds_name_key; Type: CONSTRAINT; Schema: public; Owner: npr
--

ALTER TABLE ONLY public.feeds
    ADD CONSTRAINT feeds_name_key UNIQUE (name);


--
-- Name: feeds feeds_pkey; Type: CONSTRAINT; Schema: public; Owner: npr
--

ALTER TABLE ONLY public.feeds
    ADD CONSTRAINT feeds_pkey PRIMARY KEY (id);


--
-- Name: feeds feeds_url_key; Type: CONSTRAINT; Schema: public; Owner: npr
--

ALTER TABLE ONLY public.feeds
    ADD CONSTRAINT feeds_url_key UNIQUE (url);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: npr
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: npr
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);


--
-- Name: posts posts_url_key; Type: CONSTRAINT; Schema: public; Owner: npr
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_url_key UNIQUE (url);


--
-- Name: users users_name_key; Type: CONSTRAINT; Schema: public; Owner: npr
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_name_key UNIQUE (name);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: npr
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: feed_follows fk_feed; Type: FK CONSTRAINT; Schema: public; Owner: npr
--

ALTER TABLE ONLY public.feed_follows
    ADD CONSTRAINT fk_feed FOREIGN KEY (feed_id) REFERENCES public.feeds(id) ON DELETE CASCADE;


--
-- Name: posts fk_feed; Type: FK CONSTRAINT; Schema: public; Owner: npr
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fk_feed FOREIGN KEY (feed_id) REFERENCES public.feeds(id) ON DELETE CASCADE;


--
-- Name: feeds fk_user; Type: FK CONSTRAINT; Schema: public; Owner: npr
--

ALTER TABLE ONLY public.feeds
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: feed_follows fk_user; Type: FK CONSTRAINT; Schema: public; Owner: npr
--

ALTER TABLE ONLY public.feed_follows
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

